### ISSUE TITLE
[BUG] Covers are not updated with Emby

### ISSUE THREAD

**Issue by duriTANK** [LeoKlaus/plappa#184]
**Describe the bug**
Book covers edited in an Emby server fail to load or updated. Even tried signing out and back in; deleting and the whole server.

**To Reproduce**
Not sure, just connected to my server that was all.

**Expected behavior**
I expected the plappa app to show the same covers as the Emby server has.

**Screenshots**
![IMG_3813](https://github.com/user-attachments/assets/462678b2-56de-48e2-8809-828af6f608e7)
![IMG_3812](https://github.com/user-attachments/assets/64def09e-cea1-4d95-bc90-fd3482accce8)

**Logs**
If applicable, add logs from plappa (Settings->Get Debug Logs) or Jellyfin (Dashboard->Advanced->Logs).

[9/5/2024, 7:39 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:39 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:39 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:39 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:39 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:40 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:40 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:40 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:40 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:40 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:40 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:53 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:53 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:54 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:54 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:54 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:54 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:55 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:55 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:55 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:55 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:55 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:56 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:56 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:56 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:56 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [JellyfinAPIHandler] Successfully connected to server!
[9/5/2024, 7:57 PM] [JellyfinAPIHandler] Connected to an Emby server.
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:57 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:57 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:57 PM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:57 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [JellyfinAPIHandler] Successfully connected to server!
[9/5/2024, 7:58 PM] [JellyfinAPIHandler] Connected to an Emby server.
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"LocalAddress\", intValue: nil) (\"LocalAddress\").", underlyingError: nil))

**Environment(please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 18.0 tried in 17.5.1
 - Version 1.4.2 tried on normal release as well
 - Server Version Emby 4.8.8.0

**Additional context**

**Comment by LeoKlaus** [comment]
Hi duriTANK, thank you for reporting this! It seems that this issue is caused by another issue, namely this:
```
[9/5/2024, 7:58 PM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "LocalAddress", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: "LocalAddress", intValue: nil) ("LocalAddress").", underlyingError: nil))
```

I've now implemented a fix, but the update is waiting for approval. I'll let you know once it's ready to test!

**Comment by duriTANK** [comment]
Thank you! that was so fast!

**Comment by LeoKlaus** [comment]
Update 1.4.3 is now live on the AppStore and in TestFlight, so I'll consider this as closed. Feel free to reopen if it isn't.

**Comment by duriTANK** [comment]
Just updated to the latest version as recommended; same exact issue is still going on; with the same exact log error:

9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Error downloading cover: Error Domain=plappa.AuthenticationError Code=0
[9/22/2024, 1:31 AM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "ProductName", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"ProductName\", intValue: nil) (\"ProductName\").", underlyingError: nil))
[9/22/2024, 1:31 AM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.
keyNotFound(CodingKeys(stringValue: "ProductName", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"ProductName\", intValue: nil) (\"ProductName\").", underlyingError: nil))
[9/22/2024, 1:31 AM] [plappa] Encountered an error while decoding server info: The data couldn’t be read because it is missing.…

**Comment by LeoKlaus** [comment]
Thank you for the update! The logs actually show a different error, though it is a very similar one.

This entire issue is not really related to covers at all. Your server seems to return a non-standard response for the system info endpoint (/System/Info/Public). Plappa expects to find the server info in the [format outlined in the Emby API docs](https://swagger.emby.media/?staticview=true#/SystemService/getSystemInfoPublic).

I've made all those fields optional now, but the update is still waiting for review. I'll let you know once it's available in TestFlight.

**Comment by LeoKlaus** [comment]
The update (1.4.4 build 57) is now live in TestFlight.
