### ISSUE TITLE
Better Voiceover support

### ISSUE THREAD

**Issue by Neurrone** [LeoKlaus/plappa#300]
Hi,

I'm using Voiceover, the built-in screen reader on the iPhone. It mostly works with Plappa, but there are several issues preventing me from being able to use Plappa properly. I haven't spent much time with the app since I'm still looking around for suitable Audiobookshelf clients, but here's what I've encountered so far.

1. When playing a book and the miniplayer opens, the control to dismiss it to go back to the previous screen seems to be invisible to Voiceover, so I'm stuck in the expanded player view
2. Items on the previous screen (e.g, the book information) are still visible to Voiceover even when on the expanded player screen, making it confusing to use.

**Comment by LeoKlaus** [comment]
Hi Neurrone, thank you for reporting this!

The player view is actually an overlay that can be dismissed with a swipe down gesture, so it makes sense that VoiceOver doesn't handle this well.

I'll have to see how to adapt this best without drastically changing the user interface, but making the app more accessible is definitely a high priority!

**Comment by Neurrone** [comment]
Voiceover has a gesture to Dismiss an alert or return to the previous screen: a Two-finger scrub (move two fingers back and forth three times quickly, making a “z”).

If this could be made to have the same effect as the swipe gesture you mentioned, then that would solve the problem, without needing to add additional controls. This is a [Stackoverflow question about someone trying to do this](https://stackoverflow.com/questions/50939262/dismiss-ios-form-sheet-modal-via-outside-tap-voiceover-mode) and [Apple's documentation on having ViewController respond to the escape gesture](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/SupportingAccessibility.html).

Hope that helps.

**Comment by math65** [comment]
Thank you!
I was about to open an issue, and I found this one! I agree with all the issues encountered ;)

**Comment by jwlilly** [comment]
@LeoKlaus, I can take a look at this if that works for you. I will focus on this particular issue first, but its likely that there can be some improvements in other places in the app. I have quite a bit of experience with mobile accessibility.

Two things I would like to do for this issue are implement the accessibility escape action for dismissing the player and change up the accessibility information for the sheet handle (the horizontal bar at the top) to act as a close button for VoiceOver users (this would not impact any of the current visual designs. 

edit: I just realized you don't host the source code in this repo. Still, I'm happy to help out if you'd like

**Comment by LeoKlaus** [comment]
I just released an update to TestFlight to address these, if you want to try it, you can join the TestFlight beta here: https://testflight.apple.com/join/oSAekRD5

I'm still waiting for feedback regarding other changes I've made with this update, but if all goes well, these changes should be available on the AppStore in about a week.

I'll leave this issue open for now, so you can give further feedback.


@jwlilly While I genuinely appreciate the offer, I currently don't accept contributions to the codebase of plappa.

**Comment by math65** [comment]
Hi,
Thanks for the update and for your continued efforts to improve VoiceOver support.

Unfortunately, I haven’t noticed any changes since the latest update. The player is still difficult to dismiss with VoiceOver, and VoiceOver continues to read elements from the background screen (like the book details) even when the player is open, which makes navigation very confusing.

It would also really help if VoiceOver could ignore the images in the player, as they currently clutter the screen without providing useful information for screen reader users.

Thanks again for your work—it’s much appreciated!

**Comment by LeoKlaus** [comment]
That's weird, can you confirm that you're running the latest TestFlight build (build number 70)?
The build number is displayed right next to the version in the TestFlight app.

I've tested this multiple times and each time I opened the player, VoiceOver correctly switched to the player controls.
Dismissing the player is done via an accessibility action on the topmost element of the player and the action is announced as "Dismiss now playing view".

Excluding the images makes a lot of sense, I'll make sure to add that!

**Comment by math65** [comment]
Thanks for your reply!



I just checked and I do have the correct version (build 70). However, I’m still unable to perform the VoiceOver escape gesture to dismiss the player. Have you tried it yourself, and do you know exactly how to make it work in this case?



When I navigate with VoiceOver, it correctly focuses on the player controls. But once I finish exploring the elements in the player using swipe gestures, VoiceOver jumps back to the main screen underneath, as if the player isn’t fully isolating focus.



Would you like a screenshot to help clarify?

**Comment by jwlilly** [comment]
Focus can be locked into the sheet while it is displayed using this trait: https://developer.apple.com/documentation/swiftui/accessibilitytraits/ismodal

**Comment by LeoKlaus** [comment]
I finally got around to working on this, sorry for the long delay...

I think @jwlilly suggestion was exactly what was missing, and I've also added the `accessibilityAction(.escape)`-modifier to make the dismiss gesture work properly.

I just released another build (71) to TestFlight including these changes and improvements according to the suggestions Bennet made in #372.

**Comment by BrailleBennett** [comment]
This looks like it works, my only issue that I'm concerned about is the chapters and bookmarks screen, reachable from the player. I'm not sure exactly what's supposed to show and not show on that screen, but I see a list of the chapters as well as the controls, and no close button. This might just be an unrelated issue though.
