### ISSUE TITLE
[BUG] Playback stops suddenly

### ISSUE THREAD

**Issue by MarcoCantieni** [LeoKlaus/plappa#415]
After listening for a few hours in Plappa to several m4b files, playback suddenly stopped. The m4b file was streamed from Audiobookshelf and had not been downloaded to Plappa beforehand. Playback stopped at the exact same position every time, making the issue reproducible. Tapping play or pause had no effect. I scrubbed back a few seconds, and playback resumed, but only until it reached the same point in the file, where it stopped again.
I force-quit the app on iOS 26.1 and relaunched it. When I opened the same m4b file again, playback worked without any issues. Plappa even played past the point where it had previously stopped.
At first, I suspected a corrupted m4b file, but the file is flawless

**Expected behavior**
Flawless playback for hours

**Logs**
[20.11.2025, 19:35] [ConnectivityRequestHandler] Error parsing application context: Die Daten konnten nicht gelesen werden, da sie fehlen.
<private>
Context:
<private>
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [AudioBookShelfAPIHandler] Successfully posted session
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [AudioBookShelfAPIHandler] Successfully posted session
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:53] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:54] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:54] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:54] [AudioBookShelfAPIHandler] Successfully posted session
[20.11.2025, 20:54] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:54] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[20.11.2025, 20:54] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync

**Environment(please complete the following information):**
 - Device: iPhone 15
 - OS: iOS
 - Version 26.1
 - Server Version Audiobookshelf v2.30.0
- Docker for Mac Version 4.51.0

**Comment by vvstubbs** [comment]
I have this issue with Plappa, audio playback will suddenly stop. This started to happen since I upgraded the iOS 26.2. The audio is from audio book shelf self hosted service. The only difference from the above report it doesn't take a few hours at happens after 10-15 minutes, after force quit the playback proceeds without further issue. But if it happens each time I use Plappa after not using it for several hours.

**Comment by lithodora** [comment]
Experiencing the same issue and adding more insight into my experience.

Device: iPhone XR
OS: iOS 17.7.3
Plappa Version: 1.5.6
Server Version: Audiobookshelf v2.32.1

If the app is left open and the iPhone doesn't lock the issue never happens.
If the phone goes to the lock screen the playback stops in a few minutes. 
If the phone is used for another purpose the playback stops in a few minutes.

**Comment by Jamezz98** [comment]
I have the same issue.  Exactly as described by lithodora.  
As long as I start the app and leave it open without locking the phone then it will keep playing.

I am on an iPhone SE

**Comment by oleksdovz** [comment]
Similar issue on latest ios

```[4/1/2026, 23:13] [CoreDataHandler] couldn't delete file folder: Error Domain=NSCocoaErrorDomain Code=4 "“b66b75a0-1927-467a-b9b1-ef1e21408734” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/7B0A6C99-A3FC-4577-BDC6-5407F48FD885/Documents/b66b75a0-1927-467a-b9b1-ef1e21408734, NSURL=file:///var/mobile/Containers/Data/Application/7B0A6C99-A3FC-4577-BDC6-5407F48FD885/Documents/b66b75a0-1927-467a-b9b1-ef1e21408734, NSUnderlyingError=0x14fab2ee0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[4/1/2026, 23:13] [CoreDataHandler] couldn't delete file folder: Error Domain=NSCocoaErrorDomain Code=4 "“dd1aebfd-2b90-479e-8728-2905430ac27e” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/7B0A6C99-A3FC-4577-BDC6-5407F48FD885/Documents/dd1aebfd-2b90-479e-8728-2905430ac27e, NSURL=file:///var/mobile/Containers/Data/Application/7B0A6C99-A3FC-4577-BDC6-5407F48FD885/Documents/dd1aebfd-2b90-479e-8728-2905430ac27e, NSUnderlyingError=0x14fab2a90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[4/1/2026, 23:15] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:16] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:16] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:16] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:16] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:16] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:16] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:17] [AudioBookShelfAPIHandler] Successfully posted session
[4/1/2026, 23:17] [AudioBookShelfAPIHandler] Successfully posted sessions

```

**Comment by pokrface** [comment]
I am experiencing this issue near-daily and it is maddening. Only thing in the debug logs is this:

```
[1/19/2026, 12:47] [SoundHandler] Debug information: name = AVAudioSessionInterruptionNotification, object = Optional(<AVAudioSession: 0x1228243f0>), userInfo = Optional([AnyHashable("AVAudioSessionInterruptionTypeKey"): 1, AnyHashable("AVAudioSessionInterruptionReasonKey"): 0])
```

**Comment by garrickisgross** [comment]
Experiencing this as well.

**Comment by MadWalnut** [comment]
Same issue here.

**Comment by LeoKlaus** [comment]
Can you check whether you have logs or jetsam events available? You can find them in the settings app on your phone under `Privacy & Security` -> `Analytics & Improvements` -> `Analytics Data`. You can use the search bar to search for plappa.

If you have jetsam events or crash logs there, you can use the share button when viewing them to send them via mail to me at support@plappa.me

**Comment by ecspresso** [comment]
I have the same issue, but only when a book is not downloaded. I have ABS behind Caddy as a reverse proxy.

I start the app and play a book. Everything works fine.
I pause the book and leave the phone for a while.
When I play the book again, it stops playing after what I assume is when the buffered data ends.

ABS does not seem to log anything but I noticed in my Caddy log the following:
`2026/03/31 10:58:38.750 http.log.access	handled request	{"request": {"remote_ip": "REDATED", "remote_port": "REDATED", "client_ip": "REDATED", "proto": "HTTP/2.0", "method": "POST", "host": "REDATED", "uri": "/api/session/local"}, "status": 401}`

I looked at the logs for Authelia and it did not show anything, so the problem must be with the token used by Plappa for authentication?

I use Authelia and have signed in using OIDC.

> Can you check whether you have logs or jetsam events available?

I had a few JetStream logs, but nothing from today and no log with Plappa in its name.

Debug log:

```
[2026-03-31, 8:32] [ConnectivityRequestHandler] Error parsing application context: The data couldn’t be read because it is missing.
<private>
Context:
<private>
[2026-03-31, 10:09] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:09] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:09] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:09] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:09] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:09] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:10] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:10] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:11] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:11] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:11] [AudioBookShelfAPIHandler] Couldn't post session, server returned 429. URL: https://REDACTED/api/session/local
[2026-03-31, 10:11] [AudioBookShelfAPIHandler] This error occured when posting the following session: {"playmethod":1,"startTime":65771.3125,"startedAt":1774938729977,"deviceInfo":{"osVersion":"18.7.3","clientName":"plappa","clientVersion":"1.6.0","osName":"iOS"},"displayTitle":"Bookbound Bunny","displayAuthor":"Lunadea","dayOfWeek":"Tuesday","currentTime":67907.3984375,"episodeId":null,"timeListening":2136.0859375,"updatedAt":1774944673936,"libraryId":"ede2b530-8076-4063-84bf-b62f17bc4846","date":"2026-03-31","mediaType":"book","libraryItemId":"42e888e3-5cdf-4af4-a4bc-2d78e3d68a34","mediaMetadata":{"genres":[],"title":"Bookbound Bunny"},"id":"314E8FEA-DE90-4DA9-A3DB-691975FCE467"}
[2026-03-31, 10:11] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:58] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:58] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-03-31, 10:58] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3
```

_(FYI [Caddy MIB](https://github.com/fabriziosalmi/caddy-mib) banned my phone at 10:11 because of too many 401. It was unbanned 10:21 and has not been banned yet.)_

**Comment by LeoKlaus** [comment]
Thank you for the detailed information @ecspresso! I'm assuming the issue is that the access token expires during playback. Plappa itself will refresh the token at that point, but AVFoundation offers no way (at least to my knowledge) to update the headers for an asset during playback.

Essentially, plappa would have to stop playback and restart it whenever the access token is refreshed. I'll see how I can handle this.

**Comment by LeoKlaus** [comment]
I've just released an update to TestFlight that should address this. If you're not already using the TestFlight version, you can download it here: https://testflight.apple.com/join/oSAekRD5

**Comment by ecspresso** [comment]
I'll join the TestFlight and report back here.

**Comment by jambalayajones** [comment]
> Thank you for the detailed information [@ecspresso](https://github.com/ecspresso)! I'm assuming the issue is that the access token expires during playback. Plappa itself will refresh the token at that point, but AVFoundation offers no way (at least to my knowledge) to update the headers for an asset during playback.
> 
> Essentially, plappa would have to stop playback and restart it whenever the access token is refreshed. I'll see how I can handle this.





I've been having the same issue, I'll paste the logs in case they help




[4/4/2026, 8:28 PM] [ConnectivityRequestHandler] Error parsing application context: The data couldn’t be read because it is missing.

<private>

Context:

<private>

[4/4/2026, 9:28 PM] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3

...

[4/4/2026, 9:59 PM] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=3

**Comment by ecspresso** [comment]
Plappa version: 1.6.1

Still getting the same error. Plappa is trying to post to /api/session/local but it is getting 401 responses.
(Same error message in Caddy as before)

**Comment by pthoelken** [comment]
Same issue here.

**Comment by lithodora** [comment]
Me again. 

New phone. iPhone 13
Plappa 1.6.2

I was NOT on test flight and had the same issue. I joined the test flight and issue persists 


[5/20/2026, 6:59 PM] [CoreDataHandler] Initializing core data store...
[5/20/2026, 6:59 PM] [CoreDataHandler] CoreData store initialized
[5/20/2026, 6:59 PM] [PlaybackStateHandler] Syncing playback states through server
[5/20/2026, 6:59 PM] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[5/20/2026, 6:59 PM] [PlaybackSessionHandler] Syncing playback sessions through server
[5/20/2026, 6:59 PM] [AudioBookShelfAPIHandler] Successfully posted sessions
[5/20/2026, 6:59 PM] [AudioBookShelfAPIHandler] Ignoring book <private> as it doesn't have any audio files.
[5/20/2026, 6:59 PM] [AudioBookShelfAPIHandler] Ignoring book <private> as it doesn't have any audio files.
[5/20/2026, 6:59 PM] [AudioBookShelfAPIHandler] Ignoring book <private> as it doesn't have any audio files.
[5/20/2026, 6:59 PM] [AudioBookShelfAPIHandler] Ignoring book <private> as it doesn't have any audio files.
[5/20/2026, 6:59 PM] [AudioBookShelfAPIHandler] Ignoring book <private> as it doesn't have any audio files.

**Comment by ecspresso** [comment]
Here is another log (on test flight):

<details>
  <summary>Debug log</summary>

  ```
[2026-05-16, 11:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115ae5f20 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b273f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b253e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b254d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b26910 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=unsatisfied (No network route), interface: utun5[lte], scoped, ipv4, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b24f30 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b24c60 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=unsatisfied (No network route), interface: utun5[lte], scoped, ipv4, expensive, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b27990 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b26d90 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:48] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1005 UserInfo={_kCFStreamErrorCodeKey=53, NSUnderlyingError=0x115b245d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 UserInfo={_kCFStreamErrorCodeKey=53, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:48] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115adf4b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:48] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x115b25d70 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, estimated upload: 65536Bps, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:49] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1005 UserInfo={_kCFStreamErrorCodeKey=53, NSUnderlyingError=0x115ae5fe0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 UserInfo={_kCFStreamErrorCodeKey=53, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 11:49] [PlaybackSessionHandler] Couldn't sync session: Error Domain=NSURLErrorDomain Code=-1009 UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x10e882700 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=<private>, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: utun5[lte], scoped, ipv4, ipv6, dns, expensive, uses cell}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=1}
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:16] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:39] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:39] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:39] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:39] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:39] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:40] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:40] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:40] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:40] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:40] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:40] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:41] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:41] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:41] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:41] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:41] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:41] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:42] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:42] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:42] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:42] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:42] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:42] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:48] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 15:48] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:29] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:29] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:29] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:29] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:30] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:30] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:30] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:30] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:30] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:30] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:31] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:31] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:31] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:31] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:33] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:34] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:34] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:34] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:34] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:34] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:34] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:35] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:35] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:35] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:35] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:35] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:35] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:36] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:36] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:36] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:36] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:36] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 16:36] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:17] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:18] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:19] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:19] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:19] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:19] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:20] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:20] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:20] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:43] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:44] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:45] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:46] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:47] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
[2026-05-16, 17:48] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:48] [ConnectivityRequestHandler] Watch app is not installed, skipping context sync
[2026-05-16, 17:48] [PlaybackSessionHandler] Couldn't sync session: Error Domain=plappa.AuthenticationError Code=0
  ```
</details>

**Comment by LeoKlaus** [comment]
I've just released 1.6.2 build 79 to TestFlight which allows you to authenticate with an API token instead of the usual JWT token. You can also switch to an API token without logging out through the new "Change API key" section in the settings tab.

While this is not a great solution, this should allow you to use plappa without interruptions for now.

I'm still working on a complete rewrite of the app which also moves to the new undocumented endpoints for playback that don't require authentication. I'll post both here and in the plappa Discord once that version is ready to be tested.

**Comment by ecspresso** [comment]
Just wanted to confirm that using API key works. I had to logout and login again with the API key instead (just setting the API key in settings did not work). Thanks!

EDIT: comment with the right account

**Comment by JoeRu** [comment]
Hi,
the Problem also occurs when you are behind a proxy like nginx or traefic; ABS has a short connection timer (5s) - if your proxy has a longer connection timer the proxy try to connect to a closed connection. - For Traefic 
```
    audiobookshelf-service:
       loadBalancer:
#          passHostHeader: true
        serversTransport: shortidle
        servers:
          - url:
```         
and on tail:
```
serversTransports:
    # Audiobookshelf (Node.js) advertises "Keep-Alive: timeout=5" and closes
    # idle backend connections after ~5s. Traefik's default idleConnTimeout is
    # 90s, so it kept reusing sockets the backend had already closed -> instant
    # EOF. Go's transport will not retry non-idempotent requests, so POSTs
    # (/api/session/local, /login) surfaced as 502s in ~1-40ms.
    # Expiring pooled conns before the backend does removes the race.
    shortidle:
      forwardingTimeouts:
        idleConnTimeout: 3s
```

or an nginx example:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      "";
}

upstream audiobookshelf {
    server 127.0.0.1:13378;

    # Audiobookshelf (Node.js) advertises "Keep-Alive: timeout=5" and closes
    # idle backend connections after ~5s. nginx's default upstream
    # keepalive_timeout is 60s, so it kept reusing sockets the backend had
    # already closed -> instant EOF. nginx will not retry non-idempotent
    # requests, so POSTs (/api/session/local, /login) surfaced as 502s in
    # ~1-40ms. Expiring pooled conns before the backend does removes the race.
    keepalive 16;
    keepalive_timeout 3s;
    keepalive_requests 1000;
}

server {
    listen 443 ssl;
    http2 on;
    server_name audiobookshelf.example.com;

    location / {
        proxy_pass http://audiobookshelf;

        # required, otherwise nginx talks HTTP/1.0 upstream and the
        # keepalive pool above is never used
        proxy_http_version 1.1;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Upgrade    $http_upgrade;

        # equivalent of passHostHeader: true (nginx default is $proxy_host)
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 0;
        proxy_read_timeout 300s;
    }
}
```
